ALTER TABLE users
    ADD COLUMN type VARCHAR(50);
ALTER TABLE users
    ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users
    ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users
    ALTER COLUMN name DROP NOT NULL;