name: Deploy

on:
  push:
    branches: ["release/*"]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Dar permissão ao gradlew
        run: chmod +x gradlew

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e push (ARM64)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --push \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:${GITHUB_SHA} \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:latest \
            .