name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build e push
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:latest \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:${{ github.sha }} \
            --push .