name: Deploy

on:
  push:
    branches: ["release/*"]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Definir versão da release
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: Configurar AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e push (multi-arch)
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:latest \
            -t 096000969109.dkr.ecr.us-east-1.amazonaws.com/simulacert-api:${IMAGE_TAG} \
            --push .